import { createClient } from "@supabase/supabase-js";

export type AdminNote = {
  id: string;
  author: string;
  content: string;
  created_at: string;
};

// Base Submission type (compatible with app/page.tsx insertion where id/created_at are generated by DB)
export type Submission = {
  id?: string | number;
  employee_name?: string;
  department: string;
  affected_area: string;
  work_type: string;
  friction: string;
  frequency: string;
  people_impacted: string;
  expected_support: string;
  systems_involved: string[];
  desired_outcome: string;
  created_at?: string;
  // Extended Admin Fields
  status?: "New" | "Under Review" | "Approved" | "Completed" | "Rejected" | "Implemented";
  tags?: string[];
  admin_notes?: AdminNote[];
  assigned_owner?: string;
};

// Strongly typed for the Admin Dashboard where id and created_at are guaranteed to exist
export type AdminSubmission = Submission & {
  id: string;
  created_at: string;
};

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Clean check to see if Supabase variables are set
export const isSupabaseConfigured = Boolean(
  supabaseUrl && 
  supabaseAnonKey && 
  !supabaseUrl.includes("placeholder") && 
  !supabaseAnonKey.includes("placeholder")
);

// Resilient client initialization
export const supabase = createClient(
  supabaseUrl || "https://ypxprdircaowsplnuutr.supabase.co", 
  supabaseAnonKey || "placeholder"
);